version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Preprocessing data..."
      - python preprocess.py

  build:
    commands:
      - echo "Training and logging models..."
      - python train.py

  post_build:
    commands:
      - echo "Registering and promoting the best model..."
      - python register_promote.py
      - echo "Fetching model URI..."
      - python get_model_uri.py
      - export MODEL_URI=$(cat model_uri.txt)
      - echo "Building Docker image..."
      - mlflow models build-docker -m $MODEL_URI -n mlflow-pyfunc
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 207567773639.dkr.ecr.us-east-1.amazonaws.com
      - echo "Pushing Docker image to ECR..."
      - docker push 207567773639.dkr.ecr.us-east-1.amazonaws.com/mlflow-pyfunc
      - echo "Deploying to SageMaker..."
      - python deploy.py

artifacts:
  files:
    - '**/*'
