version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Preprocessing data..."
      - python preprocess.py

  build:
    commands:
      - echo "Training and logging models..."
      - python train.py

  post_build:
    commands:
      - echo "Registering and promoting the best model..."
      - python register_promote.py
      - echo "Deploying to SageMaker..."
      - python deploy.py

artifacts:
  files:
    - '**/*'
